// Glyph shown for each loot item in the Sell window and hotbar.
export const ITEM_ICON = {
  Coal: '🪨',
  Bone: '🦴',
  Skull: '💀',
  Mushroom: '🍄',
  Anchor: '⚓',
  Gem: '💎',
  'Beaded Bracelet': '📿',
  Coin: '🪙',
  'Brass Bell': '🔔',
  Binoculars: '🔭',
  'Iron Bar': '🔩',
  'Pirate Hat': '🏴‍☠️',
  Anvil: '⚒️',
  Dagger: '🗡️',
  TNT: '🧨',
  Bomb: '💣',
  Helmet: '🪖',
  Quartz: '🔹',
  Emerald: '🟢',
  'Porcelain Vase': '🏺',
  Amethyst: '🟣',
}
